# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_answerpoll_poll_pollvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPollResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Profile')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Poll')),
                ('poll_varint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.PollVariant')),
            ],
        ),
    ]
