# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_answerpollresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerPollResult',
            new_name='AnswerPollVote',
        ),
    ]
