# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_answerpollvotemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerPollVoteManager',
        ),
    ]
