# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_delete_answerpollvotemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpollvote',
            name='answer_poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.AnswerPoll'),
        ),
    ]
