# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0010_universalquestionlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='answer_poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.UniversalQuestion'),
        ),
    ]
