# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0012_auto_20180614_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answerlike',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerlike',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answerpoll',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='author',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerLike',
        ),
        migrations.DeleteModel(
            name='AnswerPoll',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionLike',
        ),
    ]
